// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAybQ3uf6JEgExcAqI5gkQZ0u40Z4Gwizs',
    appId: '1:295348428652:web:2082d40d394f0ce16ddd49',
    messagingSenderId: '295348428652',
    projectId: 'authflowbuilderbloc',
    authDomain: 'authflowbuilderbloc.firebaseapp.com',
    storageBucket: 'authflowbuilderbloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX5rvhBl-XMDxTELQOUp_69TwZ3gVOkns',
    appId: '1:295348428652:android:a21a48dc750aaf5b6ddd49',
    messagingSenderId: '295348428652',
    projectId: 'authflowbuilderbloc',
    storageBucket: 'authflowbuilderbloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUtynJe7GGZKCZRCJFopRa4eHUOpftmOs',
    appId: '1:295348428652:ios:552c6d7779b212d46ddd49',
    messagingSenderId: '295348428652',
    projectId: 'authflowbuilderbloc',
    storageBucket: 'authflowbuilderbloc.appspot.com',
    iosClientId:
        '295348428652-2vteeec6lmu5lfgdn0eg2dhpt14p2hd9.apps.googleusercontent.com',
    iosBundleId: 'com.getnerdify.flutterAuthFlowBuilderBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUtynJe7GGZKCZRCJFopRa4eHUOpftmOs',
    appId: '1:295348428652:ios:552c6d7779b212d46ddd49',
    messagingSenderId: '295348428652',
    projectId: 'authflowbuilderbloc',
    storageBucket: 'authflowbuilderbloc.appspot.com',
    iosClientId:
        '295348428652-2vteeec6lmu5lfgdn0eg2dhpt14p2hd9.apps.googleusercontent.com',
    iosBundleId: 'com.getnerdify.flutterAuthFlowBuilderBloc',
  );
}
